export enum Race {
  HUMAN = "HUMAN",
  ELF = "ELF",
  DWARF = "DWARF",
  HALFLING = "HALFLING",
  DRAGONBORN = "DRAGONBORN",
  GNOME = "GNOME",
  HALF_ELF = "HALF_ELF",
  HALF_ORC = "HALF_ORC",
  TIEFLING = "TIEFLING",
  AASIMAR = "AASIMAR",
  GENASI = "GENASI",
  TABAXI = "TABAXI",
  TORTLE = "TORTLE",
}

export enum CharacterClass {
  BARBARIAN = "BARBARIAN",
  BARD = "BARD",
  CLERIC = "CLERIC",
  DRUID = "DRUID",
  FIGHTER = "FIGHTER",
  MONK = "MONK",
  PALADIN = "PALADIN",
  RANGER = "RANGER",
  ROGUE = "ROGUE",
  SORCERER = "SORCERER",
  WARLOCK = "WARLOCK",
  WIZARD = "WIZARD",
  ARTIFICER = "ARTIFICER",
}

export enum Alignment {
  LAWFUL_GOOD = "LAWFUL_GOOD",
  NEUTRAL_GOOD = "NEUTRAL_GOOD",
  CHAOTIC_GOOD = "CHAOTIC_GOOD",
  LAWFUL_NEUTRAL = "LAWFUL_NEUTRAL",
  TRUE_NEUTRAL = "TRUE_NEUTRAL",
  CHAOTIC_NEUTRAL = "CHAOTIC_NEUTRAL",
  LAWFUL_EVIL = "LAWFUL_EVIL",
  NEUTRAL_EVIL = "NEUTRAL_EVIL",
  CHAOTIC_EVIL = "CHAOTIC_EVIL",
}

export enum SkillName {
  ACROBATICS = "ACROBATICS",
  ANIMAL_HANDLING = "ANIMAL_HANDLING",
  ARCANA = "ARCANA",
  ATHLETICS = "ATHLETICS",
  DECEPTION = "DECEPTION",
  HISTORY = "HISTORY",
  INSIGHT = "INSIGHT",
  INTIMIDATION = "INTIMIDATION",
  INVESTIGATION = "INVESTIGATION",
  MEDICINE = "MEDICINE",
  NATURE = "NATURE",
  PERCEPTION = "PERCEPTION",
  PERFORMANCE = "PERFORMANCE",
  PERSUASION = "PERSUASION",
  RELIGION = "RELIGION",
  SLEIGHT_OF_HAND = "SLEIGHT_OF_HAND",
  STEALTH = "STEALTH",
  SURVIVAL = "SURVIVAL",
}

export enum AbilityName {
  STRENGTH = "STRENGTH",
  DEXTERITY = "DEXTERITY",
  CONSTITUTION = "CONSTITUTION",
  INTELLIGENCE = "INTELLIGENCE",
  WISDOM = "WISDOM",
  CHARISMA = "CHARISMA",
}

export enum NPCRole {
  MERCHANT = "MERCHANT",
  ALLY = "ALLY",
  ENEMY = "ENEMY",
  QUEST_GIVER = "QUEST_GIVER",
  VILLAIN = "VILLAIN",
}

export interface MulticlassDto {
  class: CharacterClass;
  level: number;
}
